swagger: "2.0"
info:
  version: 0.0.1
  title: Swagger Petstore
  description: A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification
host: 127.0.0.1:9000
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/user:
    post:
      tags:
        - Registration
        - Users
      description: |
        Register new user
      parameters:
        - name: body
          in: body
          description: Users data
          required: true
          schema:
            $ref: '#/definitions/CreateUserRequest'
      responses:
        201:
          description: User successfully created
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ApiErrorResponse'

definitions:

  ApiError:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string

  ApiErrorResponse:
    required:
      - error
      - data
    properties:
      error:
        type: object
        schema:
          $ref: '#/definitions/ApiError'
      data:
        type: object

  CreateUserRequest:
    required:
      - login
      - password
      - confirm_password
    properties:
      login:
        type: string
      password:
        type: string
      confirm_password:
        type: string
