swagger: "2.0"
info:
  version: 0.0.1
  title: Swagger Petstore
  description: A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification
host: 127.0.0.1:9000
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/user:
    post:
      tags:
        - Registration
        - Users
      description: |
        Register new user
      parameters:
        - name: body
          in: body
          description: Users data
          required: true
          schema:
            $ref: '#/definitions/CreateUserRequest'
      responses:
        201:
          description: User successfully created
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ApiErrorResponse'

  /v1/login:
    post:
      tags:
        - Registration
        - Users
      description: |
        Register new user
      parameters:
        - name: body
          in: body
          description: Users data
          required: true
          schema:
            $ref: '#/definitions/LoginRequest'
      responses:
        201:
          description: User successfully created
          schema:
            properties:
              token:
                type: string
        403:
          description: Invalid login or password
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ApiErrorResponse'

  /v1/storehouses:
    get:
      tags:
        - StoreHouse
      description: |
        Get all storehouses
      parameters:
        - in: header
          name: 'token'
          description: Authorization token
          required: true
          type: string
      responses:
        200:
          description: User successfully created
          schema:
            type: array
            items:
              $ref: '#/definitions/StoreHouseObject'
        403:
          description: Login required
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ApiErrorResponse'
  /v1/storehouse:
    post:
      tags:
        - StoreHouse
      description: |
        Create storehouse
      parameters:
        - in: header
          name: 'token'
          description: Authorization token
          required: true
          type: string
        - name: body
          in: body
          description: Users data
          required: true
          schema:
            $ref: '#/definitions/CreateStoreHouseObject'
      responses:
        201:
          description: Storehouse successfully created
        403:
          description: Login required
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ApiErrorResponse'
    delete:
      tags:
        - StoreHouse
      description: |
        Delete storehouse
      parameters:
        - in: header
          name: 'token'
          description: Authorization token
          required: true
          type: string
        - name: body
          in: body
          description: Users data
          required: true
          schema:
            $ref: '#/definitions/DeleteStoreHouseObject'
      responses:
        204:
          description: Storehouse successfully deleted
        403:
          description: Login required
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ApiErrorResponse'

  /v1/products:
    get:
      tags:
        - Product
      description: |
        Get all products
      parameters:
        - in: header
          name: 'token'
          description: Authorization token
          required: true
          type: string
      responses:
        200:
          description: Products list
          schema:
            type: array
            items:
              $ref: '#/definitions/ProductObject'
        403:
          description: Login required
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ApiErrorResponse'
  /v1/product:
    post:
      tags:
        - Product
      description: |
        Create product
      parameters:
        - in: header
          name: 'token'
          description: Authorization token
          required: true
          type: string
        - name: body
          in: body
          description: Product data
          required: true
          schema:
            $ref: '#/definitions/CreateProductObject'
      responses:
        201:
          description: Product successfully created
        403:
          description: Login required
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ApiErrorResponse'
    delete:
      tags:
        - Product
      description: |
        Delete product
      parameters:
        - in: header
          name: 'token'
          description: Authorization token
          required: true
          type: string
        - name: body
          in: body
          description: Users data
          required: true
          schema:
            $ref: '#/definitions/DeleteProductObject'
      responses:
        204:
          description: Storehouse successfully deleted
        403:
          description: Login required
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ApiErrorResponse'

  /v1/waybills:
    get:
      tags:
        - Waybill
      description: |
        Get all waybills
      parameters:
        - in: header
          name: 'token'
          description: Authorization token
          required: true
          type: string
      responses:
        200:
          description: Waybills list
          schema:
            type: array
            items:
              $ref: '#/definitions/WaybillObject'
        403:
          description: Login required
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ApiErrorResponse'
  /v1/waybill:
    post:
      tags:
        - Waybill
      description: |
        Create waybill
      parameters:
        - in: header
          name: 'token'
          description: Authorization token
          required: true
          type: string
        - name: body
          in: body
          description: Product data
          required: true
          schema:
            $ref: '#/definitions/CreateWaybillObject'
      responses:
        201:
          description: Waybill successfully created
        403:
          description: Login required
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ApiErrorResponse'
    delete:
      tags:
        - Waybill
      description: |
        Delete waybill
      parameters:
        - in: header
          name: 'token'
          description: Authorization token
          required: true
          type: string
        - name: body
          in: body
          description: Users data
          required: true
          schema:
            $ref: '#/definitions/ProcessWaybillObject'
      responses:
        204:
          description: Waybill successfully deleted
        403:
          description: Login required
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ApiErrorResponse'
    put:
      tags:
        - Waybill
      description: |
        Process waybill
      parameters:
        - in: header
          name: 'token'
          description: Authorization token
          required: true
          type: string
        - name: body
          in: body
          description: Users data
          required: true
          schema:
            $ref: '#/definitions/ProcessWaybillObject'
      responses:
        200:
          description: Waybill successfully processed
        403:
          description: Login required
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ApiErrorResponse'

definitions:
  ApiError:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string

  ApiErrorResponse:
    required:
      - error
      - data
    properties:
      error:
        type: object
        schema:
          $ref: '#/definitions/ApiError'
      data:
        type: object

  CreateUserRequest:
    required:
      - login
      - password
      - confirm_password
    properties:
      login:
        type: string
      password:
        type: string
      confirm_password:
        type: string
  LoginRequest:
    required:
      - login
      - password
    properties:
      login:
        type: string
      password:
        type: string

  StoreHouseObject:
    properties:
      _id:
        type: string
      title:
        type: string
      capacity:
        type: number
      used_space:
        type: number
  CreateStoreHouseObject:
    required:
      - title
      - capacity
    properties:
      title:
        type: string
      capacity:
        type: number
  DeleteStoreHouseObject:
    required:
      - storehouse_id
    properties:
      storehouse_id:
        type: string

  ProductObject:
    properties:
      _id:
        type: string
      title:
        type: string
      size:
        type: number
  CreateProductObject:
    required:
      - title
      - size
    properties:
      title:
        type: string
      size:
        type: number
  DeleteProductObject:
    required:
      - product_id
    properties:
      product_id:
        type: string

  WaybillObject:
    properties:
      _id:
        type: string
      storehouse_id:
        type: string
      storehouse_title:
        type: string
      product_id:
        type: string
      product_title:
        type: string
      count:
        type: number
      action:
        type: string
  CreateWaybillObject:
    required:
      - storehouse_id
      - storehouse_title
      - product_id
      - product_title
      - count
      - action
    properties:
      storehouse_id:
        type: string
      storehouse_title:
        type: string
      product_id:
        type: string
      product_title:
        type: string
      count:
        type: number
      action:
        type: string
        enum: [in, out, move]
  ProcessWaybillObject:
    required:
      - product_id
    properties:
      product_id:
        type: string
