from .registration import registration_handler
from .login import login_handler
from .storehouse import get_store_houses_handler, create_store_house_handler, delete_store_house_handler
from .products import get_products_handler, create_product_handler, delete_product_handler
from .waybill import create_waybill_handler, get_waybills_handler, delete_waybill_handler, process_waybill_handler
